[package]
name = "car_reader"
version = "0.1.0"
edition = "2021"

[lib]
name = "car_reader_lib"
path = "src/lib.rs"

[[bin]]
name = "car_reader"
path = "src/main.rs"

[dependencies]
uuid = "1.3.0"
binrw = "0.11.0"
