[package]
name = "car_reader"
version = "0.1.0"
edition = "2021"

[lib]
name = "car_reader_lib"
path = "src/lib.rs"

[[bin]]
name = "car_reader"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
binrw = "0.11.0"
clap = { version = "4.1.13", features = ["derive"] }
uuid = "1.3.0"
